AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - config.ru
    - db/schema.rb

Metrics/BlockLength:
  Exclude:
    - 'app/admin/*.rb'
    - 'config/routes.rb'
    - 'lib/tasks/**/*.rake'
    - 'spec/**/*.rb'
