sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4
services:
  - postgresql
  - elasticsearch
  - redis-server
before_script:
  - sleep 10
script:
  - bundle exec rails db:create
  - bundle exec rails db:schema:load
  - bundle exec rails spec
  - bundle exec codeclimate-test-reporter
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - RAILS_ENV=test
