sudo: false
language: ruby
cache: bundler
rvm:
  - 2.4
services:
  - postgresql
  - elasticsearch
before_script:
  - sleep 10
script:
  - bundle exec rake db:create
  - bundle exec rake db:migrate
  - bundle exec rake spec
  - bundle exec codeclimate-test-reporter
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
    - RAILS_ENV=test
