applications:
- name: publish-data-beta-production-worker
  memory: 1G
  buildpack: https://github.com/cloudfoundry/ruby-buildpack.git#v1.7.34
  stack: cflinuxfs3
  command: bundle exec sidekiq
  env:
    RAILS_ENV: production
    RACK_ENV: production
  services:
  - publish-production-secrets
  - publish-beta-production-pg
  - publish-beta-production-redis
  - logit-ssl-drain
  - elasticsearch-6-beta-production
  health-check-type: process
