applications:
- name: publish-data-beta
  command: bundle exec rake db:migrate && bin/rails server -b 0.0.0.0 -p $PORT -e $RAILS_ENV
  memory: 512M
  buildpack: https://github.com/cloudfoundry/ruby-buildpack.git#v1.7.14
  env:
    RAILS_ENV: production
    RACK_ENV: production
  services:
  - beta-production-elasticsearch
  - publish-beta-production-pg
  - publish-production-secrets
  - logit-ssl-drain
  - dgu-prometheus
