default: &default
  host: '<%= ENV['REDIS_IP'] || "localhost" %>'
  port: '<%= ENV['REDIS_PORT'] || 6379 %>'
  db: 12
  network_timeout: 5

development:
  <<: *default
  namespace: development

test:
  <<: *default
  namespace: test

staging:
  <<: *default
  namespace: staging
  password: '<%= ENV['REDIS_PASSWORD'] %>'

production:
  <<: *default
  namespace: production
  password: '<%= ENV['REDIS_PASSWORD'] %>'
