---
:concurrency: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

staging:
  :schedule:
    ckan_v26_sync:
      class: CKAN::V26::SyncWorker
      cron: '*/10 * * * *'

production:
  :queues:
    - default
    - importer
    - indexer
    - link_checker

  :schedule:
    beta_update:
      class: BetaUpdateWorker
      cron: '0 0 * * * *' # Runs every hour
