---
:concurrency: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

staging:
  :schedule:
    ckan_v26_sync:
      class: CKAN::V26::SyncWorker
      cron: '*/10 * * * *'

production:
  :schedule:
    ckan_v26_sync:
      class: CKAN::V26::SyncWorker
      cron: '*/10 * * * *'
